version: '3'
services:
  app:
    image: maven:latest
    volumes: 
      - ./src:/backend/src          
      - ./target:/backend/target  
      - ./.mvn:/backend/.mvn
      - ./pom.xml:/backend/pom.xml

    working_dir: /backend
    ports:
      - "8080:8080"
    command: mvn spring-boot:run

  postgres:
    container_name: trvelogdata
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d