version: '3'
services:
  app:
    image: maven:latest
    volumes: 
      - ./auth_service/src:/backend/auth_service/src          
      - ./auth_service/target:/backend/auth_service/target  
      - ./auth_service/.mvn:/backend/auth_service/.mvn
      - ./auth_service/pom.xml:/backend/auth_service/pom.xml

    working_dir: /backend/auth_service
    ports:
      - "8080:8080"
    command: mvn spring-boot:run

  postgres:
    container_name: trvelogdata
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d