package backend.travel_service.utils;

import java.util.*;

public class CountryContinentMapping {
    public static final Map<String, List<String>> continentToCountries = new HashMap<>();

    static {
        continentToCountries.put(
                "Africa",
                Arrays.asList(
                        "Algeria",
                        "Angola",
                        "Benin",
                        "Botswana",
                        "Burkina Faso",
                        "Burundi",
                        "Cameroon",
                        "Cape Verde",
                        "Central African Republic",
                        "Chad",
                        "Comoros",
                        "Democratic Congo",
                        "Congo",
                        "Djibouti",
                        "Egypt",
                        "Equatorial Guinea",
                        "Eritrea",
                        "Eswatini",
                        "Ethiopia",
                        "Gabon",
                        "Gambia",
                        "Ghana",
                        "Guinea",
                        "Guinea-Bissau",
                        "Côte d'Ivoire",
                        "Kenya",
                        "Lesotho",
                        "Liberia",
                        "Libya",
                        "Madagascar",
                        "Malawi",
                        "Mali",
                        "Mauritania",
                        "Mauritius",
                        "Morocco",
                        "Mozambique",
                        "Namibia",
                        "Niger",
                        "Nigeria",
                        "Rwanda",
                        "São Tomé and Príncipe",
                        "Senegal",
                        "Seychelles",
                        "Sierra Leone",
                        "Somalia",
                        "South Africa",
                        "South Sudan",
                        "Sudan",
                        "Tanzania",
                        "Togo",
                        "Tunisia",
                        "Uganda",
                        "Zambia",
                        "Zimbabwe",
                        "Canary Islands",
                        "French Southern and Antarctic Lands",
                        "Madeira",
                        "Mayotte",
                        "Réunion",
                        "Saint Helena, Ascension and Tristan da Cunha"));
        continentToCountries.put(
                "Asia",
                Arrays.asList(
                        "Afghanistan",
                        "Armenia",
                        "Azerbaijan",
                        "Bahrain",
                        "Bangladesh",
                        "Bhutan",
                        "Brunei",
                        "Cambodia",
                        "China",
                        "India",
                        "Indonesia",
                        "Iran",
                        "Iraq",
                        "Israel",
                        "Japan",
                        "Jordan",
                        "Kazakhstan",
                        "North Korea",
                        "South Korea",
                        "Kuwait",
                        "Kyrgyzstan",
                        "Laos",
                        "Lebanon",
                        "Malaysia",
                        "Maldives",
                        "Mongolia",
                        "Myanmar",
                        "Nepal",
                        "Oman",
                        "Pakistan",
                        "Philippines",
                        "Qatar",
                        "Saudi Arabia",
                        "Singapore",
                        "Sri Lanka",
                        "Syria",
                        "Tajikistan",
                        "Taiwan",
                        "Thailand",
                        "Timor-Leste",
                        "Turkey",
                        "Turkmenistan",
                        "United Arab Emirates",
                        "Uzbekistan",
                        "Vietnam",
                        "Yemen"));
        continentToCountries.put(
                "Europe",
                Arrays.asList(
                        "Albania",
                        "Andorra",
                        "Austria",
                        "Azerbaijan",
                        "Belarus",
                        "Belgium",
                        "Bosnia and Herzegovina",
                        "Bulgaria",
                        "Crotia",
                        "Cyprus",
                        "Denmark",
                        "Estonia",
                        "Finland",
                        "France",
                        "Germany",
                        "Georgia",
                        "Greece",
                        "Hungary",
                        "Iceland",
                        "Ireland",
                        "Italy",
                        "Kosovo",
                        "Latvia",
                        "Liechtenstein",
                        "Lithuania",
                        "Luxembourg",
                        "Malta",
                        "Moldova",
                        "Monaco",
                        "Montenegro",
                        "Netherlands",
                        "North Macedonia",
                        "Norway",
                        "Poland",
                        "Portugal",
                        "Romania",
                        "Russia",
                        "San Marino",
                        "Serbia",
                        "Slovakia",
                        "Slovenia",
                        "Spain",
                        "Sweden",
                        "Switzerland",
                        "Turkey",
                        "Ukraine",
                        "United Kingdom",
                        "Vatican City"));
        continentToCountries.put(
                "North America",
                Arrays.asList(
                        "Antigua and Barbuda",
                        "The Bahamas",
                        "Barbados",
                        "Belize",
                        "Canada",
                        "Costa Rica",
                        "Cuba",
                        "Dominica",
                        "Dominican Republic",
                        "El Salvador",
                        "Grenada",
                        "Guatemala",
                        "Haiti",
                        "Honduras",
                        "Jamaica",
                        "Mexico",
                        "Nicaagua",
                        "Panama",
                        "Saint Kitts and Nevis",
                        "Saint Lucia",
                        "Saint Vincent and the Grenadines",
                        "Trinidad and Tobago",
                        "United States"));
        continentToCountries.put(
                "South America",
                Arrays.asList(
                        "Argentina",
                        "Bolivia",
                        "Brazil",
                        "Chile",
                        "Colombia",
                        "Ecuador",
                        "Guyana",
                        "Paraguay",
                        "Peru",
                        "Suriname",
                        "Uruguay",
                        "Venezuela"));
        continentToCountries.put(
                "Oceania",
                Arrays.asList(
                        "Australia",
                        "Cook Islands",
                        "Federated States of Micronesia",
                        "Fiji",
                        "Kiribati",
                        "Marshall Islands",
                        "Nauru",
                        "New Zealand",
                        "Niue",
                        "Palau",
                        "Papua New Guinea",
                        "Samoa",
                        "Solomon Islands",
                        "Tonga",
                        "Tuvalu",
                        "Vanuatu"));
        continentToCountries.put("Antarctica", Arrays.asList("Antarctica"));
    }

    public static String getContinentByCountry(String country) {
        for (Map.Entry<String, List<String>> entry : continentToCountries.entrySet()) {
            if (entry.getValue().contains(country)) {
                return entry.getKey();
            }
        }
        return "Unknown";
    }
}
